# Generated by Django 4.1 on 2022-09-23 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_client', models.CharField(max_length=32)),
                ('prenom_client', models.CharField(max_length=32)),
                ('phone_client', models.CharField(max_length=32)),
                ('sexe', models.CharField(max_length=10)),
                ('cni', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Type_Decor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_decor', models.CharField(max_length=32)),
                ('montant_decor', models.IntegerField(default=0)),
                ('code_decor', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Type_Fete',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_fete', models.CharField(max_length=32)),
                ('montant_fete', models.IntegerField(default=0)),
                ('code_fete', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('avance', models.IntegerField(default=0)),
                ('a_payer', models.IntegerField(blank=True, default=0, null=True)),
                ('date_avance', models.DateTimeField(auto_now=True)),
                ('date_payer_total', models.DateField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.client')),
                ('type_decor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.type_decor')),
                ('type_fete', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.type_fete')),
            ],
        ),
    ]
