# Generated by Django 4.1 on 2022-08-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_client', models.CharField(max_length=32)),
                ('prenom_client', models.CharField(max_length=32)),
                ('phone_client', models.CharField(max_length=32)),
                ('sexe', models.CharField(max_length=2)),
                ('datedelafete', models.DateField()),
                ('nombrejr', models.IntegerField()),
                ('autres', models.TextField()),
            ],
        ),
    ]
