# Generated by Django 4.1 on 2022-08-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sallere', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salle',
            name='nomfete',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
