# Generated by Django 4.1 on 2022-08-26 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sallere', '0002_salle_nomfete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salle',
            name='sexe',
        ),
    ]
