# Generated by Django 4.1 on 2022-08-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sallere', '0003_remove_salle_sexe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salle',
            old_name='nom_client',
            new_name='nomClient',
        ),
        migrations.RenameField(
            model_name='salle',
            old_name='phone_client',
            new_name='phoneClient',
        ),
        migrations.RenameField(
            model_name='salle',
            old_name='prenom_client',
            new_name='prenomClient',
        ),
        migrations.AddField(
            model_name='salle',
            name='montantpaye',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
