# Generated by Django 4.1 on 2022-08-27 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sallere', '0005_rename_montantpaye_salle_montantapaye_salle_avance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_client', models.CharField(max_length=32)),
                ('prenom_client', models.CharField(max_length=32)),
                ('phone_client', models.CharField(max_length=32)),
                ('sexe', models.CharField(max_length=10)),
                ('cni', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('a_payer', models.IntegerField()),
                ('avance', models.IntegerField(default=0)),
                ('date_avance', models.DateTimeField(auto_now=True)),
                ('date_payer_total', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sallere.client')),
            ],
        ),
        migrations.CreateModel(
            name='Type_Decor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nomdecor', models.CharField(max_length=32)),
                ('montantdecor', models.IntegerField(default=0)),
                ('codedecor', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Type_Fete',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nomfete', models.CharField(max_length=32)),
                ('montantfete', models.IntegerField(default=0)),
                ('codefete', models.CharField(max_length=32)),
            ],
        ),
        migrations.DeleteModel(
            name='Salle',
        ),
        migrations.AddField(
            model_name='reservation',
            name='type_decor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sallere.type_decor'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='type_fete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sallere.type_fete'),
        ),
    ]
