# Generated by Django 4.1 on 2022-08-27 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sallere', '0006_client_reservation_type_decor_type_fete_delete_salle_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='type_fete',
            old_name='montantfete',
            new_name='montant_fete',
        ),
    ]
