# Generated by Django 4.1 on 2022-08-27 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sallere', '0007_rename_montantfete_type_fete_montant_fete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='type_decor',
            old_name='codedecor',
            new_name='code_decor',
        ),
        migrations.RenameField(
            model_name='type_decor',
            old_name='montantdecor',
            new_name='montant_decor',
        ),
        migrations.RenameField(
            model_name='type_fete',
            old_name='codefete',
            new_name='code_fete',
        ),
        migrations.RenameField(
            model_name='type_fete',
            old_name='nomfete',
            new_name='nom_fete',
        ),
    ]
