# Generated by Django 4.1 on 2022-08-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sallere', '0008_rename_codedecor_type_decor_code_decor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='a_payer',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_payer_total',
            field=models.DateField(blank=True, null=True),
        ),
    ]
