# Generated by Django 4.1 on 2022-08-27 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sallere', '0011_alter_reservation_a_payer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='type_decor',
            old_name='nomdecor',
            new_name='nom_decor',
        ),
    ]
