# Generated by Django 4.1 on 2022-08-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sallere', '0012_rename_nomdecor_type_decor_nom_decor'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='date_de_la_fete',
            field=models.DateField(null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='date_reservation',
            field=models.DateField(null=True),
        ),
    ]
