# Generated by Django 4.1 on 2022-08-28 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sallere', '0013_reservation_date_de_la_fete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date_reservation',
            field=models.DateField(null=True),
        ),
    ]
