# Generated by Django 4.1 on 2022-08-28 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sallere', '0014_alter_reservation_date_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='date_de_la_fete',
        ),
    ]
