# Generated by Django 2.2.28 on 2022-11-15 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sallere', '0016_remove_reservation_date_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='a_payer',
            field=models.IntegerField(default=0),
        ),
    ]
